language: minimal
sudo: required
cache:
 directories:
  - docker
services:
- docker
before_script:
 - export HOME="/home/travis"
 - curl https://toolbelt.heroku.com/install.sh | sudo sh
 #- gzip -dc docker/rails.tar.gz | docker load || true
 - env
script:
- env
- echo ${RAILS_SECRET}
#- docker build -t rails:latest --build-arg secret=${RAILS_SECRET} --cache-from=rails:latest .
#- docker run --name rails -e RAILS_ENV=test rails ./bin/rspec
#- docker save rails | gzip > docker/rails.tar.gz || true
after_success:
- export APP="stark-basin-33709"
- HEROKU_API_KEY="$APIKEY" heroku container:push --app $APP web
- HEROKU_API_KEY="$APIKEY" heroku container:release --app $APP web
