language: minimal
sudo: required
cache:
 directories:
  - docker
services:
- docker
before_script:
 - sudo snap install heroku --classic
 #- gzip -dc docker/rails.tar.gz | docker load || true
 - env
script:
- env
- echo ${RAILS_SECRET}
#- docker build -t rails:latest --build-arg secret=${RAILS_SECRET} --cache-from=rails:latest .
#- docker run --name rails -e RAILS_ENV=test rails ./bin/rspec
#- docker save rails | gzip > docker/rails.tar.gz || true
after_success:
- HEROKU_API_KEY="$APIKEY" heroku container:push web
- HEROKU_API_KEY="$APIKEY" heroku container:release web
