language: ruby
cache: bundler
services:
- docker
script:
- env
- echo ${RAILS_SECRET}
- docker build -t rails:latest --build-arg secret=${RAILS_SECRET} .
- docker run --name rails -e RAILS_ENV=test rails ./bin/rspec
deploy:
  provider: heroku
  api_key:
    secure: B4gn6q4OaOK1jUKgnIU28XB0t+OVU7EJJDTmSkEPsb69XpPtY6dcDB4kN8imOVqeK0IiLtvHRuRKJ55wRFzoMNL43UbWrD4xDvJaIpgxAQ7SQjjvjq+5mXuz6ijaYMyWfakcS7Pa5FuFrjL3gT15fQOgMcyTpyHJ1Azm7XK8T9lhjsNQEdXpRIq4W9f6qdft3hk4/5QWZCRC/aM8C5hlvQim2cyLQz/dlBlwnfTQnioyW8eD4toRTM0+SrTXqtxjk/Z6axOVGH+M8NEH3zhLuQVHoxriz0dTyAGgROvawD2K3JTQoT7YLEqlnrfHbKRr5neBW45k8LIgRlUWPSHsmNnm3hkaq43uBpd+z5R2sKd1B89oPNNx0F/RNuq5rGKf9IbXWDqHITGFvtBzjzT7GclWHV7GjGW+jVmt49pENBH1YjFotRqPZ0CrZ6HsMiV3pUxQO3aXD4QHdf+6jLzZvrB+sC2zjs3YI3xMG/4cyMv6tvY7XlkIQgnYLoxrZI6RU5NnjYby9bwo3o0DqNhnHt3q41W+x9FD86rKCeUcPBifbBUj/EM4xOdyl/yOmqggQIB8WGqjJHQf4SG0Qyb+4n/9YTBSoVmj0H31hN2X73AtKZkgRuaEThJPUmIn0xhIuLTaLC/zhi3gkAn+sdJU9/r7W97bj8qjG9nLFHVjbXQ=
  run:
  - echo "Hallo"
